# Generated by Django 4.1.1 on 2022-09-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tecnology',
            new_name='technology',
        ),
    ]
